const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const pkgPath = path.join(rootDir, "package.json");
const swPath = path.join(rootDir, "sw.js");
const indexPath = path.join(rootDir, "index.html");
const versionJsPath = path.join(rootDir, "src", "version.js");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const version = pkg.version;

console.log(`[sync-version] Synchronizing version v${version}...`);

// 1. Update sw.js
if (fs.existsSync(swPath)) {
  let swContent = fs.readFileSync(swPath, "utf8");
  swContent = swContent.replace(
    /const CACHE_NAME = ['"]esenho-v[^'"]+['"];/,
    `const CACHE_NAME = 'esenho-v${version}';`
  );
  fs.writeFileSync(swPath, swContent, "utf8");
  console.log(`[sync-version] Updated sw.js (CACHE_NAME -> esenho-v${version})`);
}

// 2. Update index.html badge
if (fs.existsSync(indexPath)) {
  let indexContent = fs.readFileSync(indexPath, "utf8");
  indexContent = indexContent.replace(
    /<span class="badge">v[^<]+<\/span>/,
    `<span class="badge">v${version}</span>`
  );
  fs.writeFileSync(indexPath, indexContent, "utf8");
  console.log(`[sync-version] Updated index.html badge (-> v${version})`);
}

// 3. Generate src/version.js
const versionJsContent = `// Auto-generated by scripts/sync-version.js — DO NOT EDIT DIRECTLY
export const VERSION = '${version}';

if (typeof module !== "undefined" && module.exports) {
  module.exports = { VERSION };
}

if (typeof globalThis !== "undefined") {
  globalThis.ESENHO_VERSION = '${version}';
}
`;
fs.writeFileSync(versionJsPath, versionJsContent, "utf8");
console.log(`[sync-version] Generated src/version.js`);

console.log(`[sync-version] Version v${version} synchronized successfully.`);
