// Auto-generated by scripts/sync-version.js — DO NOT EDIT DIRECTLY
export const VERSION = '0.8.16';

if (typeof module !== "undefined" && module.exports) {
  module.exports = { VERSION };
}

if (typeof globalThis !== "undefined") {
  globalThis.ESENHO_VERSION = '0.8.16';
}
