// Auto-generated by scripts/sync-version.js — DO NOT EDIT DIRECTLY
var ESENHO_VERSION = '0.10.158';
if (typeof globalThis !== 'undefined') {
  globalThis.ESENHO_VERSION = '0.10.158';
}
if (typeof window !== 'undefined') {
  window.ESENHO_VERSION = '0.10.158';
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { VERSION: '0.10.158' };
}
